dist: trusty

sudo: required

language: cpp

arch:
   - amd64
   - ppc64le

before_install:
   - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
   - sudo apt-get update -qq
   - if [ "$TRAVIS_CPU_ARCH" = "ppc64le" ]; then
       sudo apt-get install liblapack-dev libboost-program-options-dev -y;
     else
       sudo apt-get install g++-4.9 liblapack-dev libboost-program-options-dev -y;
     fi
     
install:
   - wget https://www.dropbox.com/s/n0zxh86y5nk65km/armadillo-6.100.1.tar.gz?dl=0
   - mv 'armadillo-6.100.1.tar.gz?dl=0' armadillo-6.100.1.tar.gz && tar xf armadillo-6.100.1.tar.gz
   - if [ "$TRAVIS_CPU_ARCH" = "ppc64le" ]; then 
       pushd armadillo-6.100.1 && CXX=/usr/bin/g++ cmake . && make && sudo make install && popd;
     else
       pushd armadillo-6.100.1 && CXX=/usr/bin/g++-4.9 cmake . && make && sudo make install && popd;
     fi

script: 
   - if [ "$TRAVIS_CPU_ARCH" = "ppc64le" ]; then
       CXX=/usr/bin/g++ make CPPFLAGS="-I../gzstream -I../dlib -D DLIB_NO_GUI_SUPPORT=1 -D DLIB_USE_BLAS=1 -D DLIB_USE_LAPACK=1 -D NO_HDF5=1" SEER_LDLIBS="-L../gzstream -lgzstream -lz -larmadillo -lboost_program_options -llapack -lblas -lpthread" && make test;
     else
       CXX=/usr/bin/g++-4.9 make CPPFLAGS="-I../gzstream -I../dlib -D DLIB_NO_GUI_SUPPORT=1 -D DLIB_USE_BLAS=1 -D DLIB_USE_LAPACK=1 -D NO_HDF5=1" SEER_LDLIBS="-L../gzstream -lgzstream -lz -larmadillo -lboost_program_options -llapack -lblas -lpthread" && make test;
     fi  
